providers = ["python"]

[phases.setup]
nixPkgs = ["python310", "gcc", "cmake"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt && pip uninstall -y opencv-python opencv-contrib-python && pip install opencv-python-headless==4.9.0.80"]

[phases.build]
cmds = ["true"]

[start]
cmd = "python main.py"
