providers = ["python"]

[phases.setup]
nixPkgs = ["python310", "gcc", "cmake"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python main.py"
