providers = ["python"]

[phases.setup]
nixPkgs = ["python310", "gcc", "cmake"]

[variables]
PIP_NO_CACHE_DIR = "1"

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt"]

[phases.build]
cmds = ["true"]

[start]
cmd = "python main.py"
